version: '3.8'

services:
  influxdb2:
    image: influxdb:2
    container_name: influxdb-compose
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: aleksandar10
      DOCKER_INFLUXDB_INIT_PASSWORD: iotPassword10
      DOCKER_INFLUXDB_INIT_ORG: Elfak
      DOCKER_INFLUXDB_INIT_BUCKET: PowerConsumption
      DOCKER_INFLUXDB_INIT_RETENTION: 0
    ports:
      - "8086:8086"
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    networks:
      - BRIDGE

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-compose
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto.conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - BRIDGE
    depends_on:
      - influxdb2
    
  nats-main:
    image: nats
    container_name: nats-compose
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - BRIDGE
    depends_on:
      - influxdb2

  grafana:
    image: grafana/grafana
    container_name: grafana-compose
    environment:
      GF_SERVER_HTTP_PORT: 4545
    ports:
      - "4545:4545"
    networks:
      - BRIDGE
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - mosquitto

  sensor:
    image: sensor:1
    container_name: sensor-compose
    networks:
      - BRIDGE
    depends_on:
      - mosquitto

  manager:
    image: emqx/ekuiper-manager
    container_name: ekuiper-manager
    ports:
    - "9082:9082"
    depends_on:
      - mosquitto
    restart: unless-stopped
    environment:
      DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081"
    networks:
      - BRIDGE
  ekuiper:
    image: lfedge/ekuiper
    ports:
      - "9081:9081"
      - "127.0.0.1:20498:20498"
    container_name: ekuiper
    hostname: ekuiper
    depends_on:
      - mosquitto
    restart: unless-stopped
    user: root
    volumes:
      - kuiper.data:/kuiper/data
      - kuiper.log:/kuiper/log
    networks:
      - BRIDGE
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://mosquitto:1883"
      KUIPER__BASIC__CONSOLELOG: "true"
      KUIPER__BASIC__IGNORECASE: "false"
  
  filter:
    image: filter:1
    container_name: filter-compose
    networks:
      - BRIDGE
    ports:
      - "1111:1111"
    depends_on:
      - sensor
    
  dashboard:
    image: dashoard:1
    container_name: dashboard-compose
    # restart: unless-stopped
    networks:
      - BRIDGE
    depends_on:
      - filter

  command:
    image: command:1
    container_name: command-compose
    networks:
      - BRIDGE
    ports:
      - "7722:7722"
    depends_on:
      - mosquitto
  
  webpage:
    image: webpage:1
    container_name: webpage-compose
    networks:
      - BRIDGE
    ports:
      - "3333:3333"
    depends_on:
      - command




volumes:
  influxdb2-data:
    external: true
    name: influxdb2-data
  influxdb2-config:
    external: true
    name: influxdb2-config
  mosquitto-data:
  mosquitto-log:
  mosquitto.conf:
    external: true
    name: mosquitto.conf
  kuiper.data:
    name: kuiper.data
    external: true
  kuiper.log:
    name: kuiper.log
    external: true
  grafana-storage:
    name: grafana-storage
    external: true

networks:
  BRIDGE:
    external: true
