version: '3.4'

services:
    manager:
       image: emqx/ekuiper-manager
       container_name: ekuiper-manager
       ports:
       - "9082:9082"
       restart: unless-stopped
       environment:
         DEFAULT_EKUIPER_ENDPOINT: "http://ekuiper:9081"
       networks:
         - BRIDGE
    ekuiper:
       image: lfedge/ekuiper
       ports:
         - "9081:9081"
         - "127.0.0.1:20498:20498"
       container_name: ekuiper
       hostname: ekuiper
       restart: unless-stopped
       user: root
       volumes:
         - kuiper.data:/kuiper/data
         - kuiper.log:/kuiper/log
       networks:
         - BRIDGE
       environment:
         MQTT_SOURCE__DEFAULT__SERVER: "tcp://mosquitto:1883"
         KUIPER__BASIC__CONSOLELOG: "true"
         KUIPER__BASIC__IGNORECASE: "false"
     
volumes:
    kuiper.data:
       name: kuiper.data
       external: true
    kuiper.log:
       name: kuiper.log
       external: true
networks:
    BRIDGE:
       external: true
    